# Generated by Django 4.0.6 on 2023-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_signup_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribstion',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
