# Generated by Django 4.0.6 on 2023-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_subscribstion_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_model',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
