# Generated by Django 4.0.6 on 2023-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_signup_model_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribstion',
            old_name='email',
            new_name='email_id',
        ),
    ]
