# Generated by Django 4.0.6 on 2023-03-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_email_subscribstion_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribstion',
            old_name='email_id',
            new_name='email',
        ),
    ]
